# This is a basic workflow to help you get started with Actions

name: CI-Build-UniMath

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build UniMath
  unimath:
    # Need a name for the job, see https://stackoverflow.com/questions/68554735/github-action-status-check-missing-from-the-list-of-checks-in-protected-branch-s
    name: Build-UniMath-and-Sanity-Checks
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      
      # Install everything needed for building UniMath (and more)
      - name: Install build dependencies
        run: sudo apt-get install build-essential git ocaml ocaml-nox ocaml-native-compilers camlp5 libgtk2.0 libgtksourceview2.0 liblablgtk-extras-ocaml-dev ocaml-findlib libnum-ocaml-dev emacs

      # Change into UniMath directory and build UniMath
      - name: Build UniMath
        run: |
          cd $GITHUB_WORKSPACE
          time make build-coq BUILD_COQIDE=$BUILD_COQIDE && time make -j2 TIMECMD=time

      # Change into UniMath directory and run sanity checks
      - name: Change into UniMath directory and run sanity checks
        run: |
          cd $GITHUB_WORKSPACE
          time make TIMECMD=time sanity-checks


      - name: Install UniMath
        run: |
          pushd $GITHUB_WORKSPACE
          make install
          export PATH=$PATH:$PWD/sub/coq/bin/
          echo $PATH
          popd





  satellites:
    needs: unimath
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Change into UniMath directory and build UniMath
      - name: Build libraries TypeTheory, Largecatmodules, and SetHITs
        run: |
          # build TypeTheory
          git clone https://github.com/UniMath/TypeTheory
          pushd TypeTheory
          make
          popd
          # build largecatmodules
          git clone https://github.com/UniMath/largecatmodules
          pushd largecatmodules
          make
          popd
          # build SetHITS
          git clone https://github.com/UniMath/SetHITs
          pushd SetHITs
          cd code
          coq_makefile -f _CoqProject -o Makefile
          make
          popd


